confluence:
  build: docker/confluence
  ports:
    - "8090:8090" # no cache
  links:
    - database
  volumes:
    - home:/opt/confluence-home
  restart: no

database:
  build: docker/postgres
  volumes:
    - tmp:/tmp # import backups
  restart: no
